<script>
    import { updateCursorByName, resetCursor } from '../components/Cursor/CursorHelper'
</script>

<h1>Home</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab eius nesciunt eligendi sed culpa consequatur assumenda nostrum dicta porro! Perspiciatis nemo hic facilis quo illo et esse impedit earum odio.</p>
<div class="box"
on:mouseover={() => updateCursorByName('first')}
on:focus={() => updateCursorByName('first')}
on:mouseout={resetCursor}
on:blur={resetCursor}></div>