export const animations = [
  {
    name: 'first',
    shape: 'polygon(25% 0%, 100% 0%, 75% 100%, 0% 100%)',
    rotation: 90,
    scale: 6,
    color: 'green',
    iconInside:'https://upload.wikimedia.org/wikipedia/commons/6/6c/SVG_Simple_Icon.svg',
    iconScale:'.5',
  },
  {
    name: 'second',
    shape: 'polygon(0% 0%, 100% 0%, 100% 75%, 75% 75%, 75% 100%, 50% 75%, 0% 75%)',
    rotation: 0,
    scale: 6,
    color: 'blue',
    iconInside:'',
    iconScale:'.5',
  },
  {
    name: 'third',
    shape: 'polygon(20% 0%, 80% 0%, 100% 100%, 0% 100%)',
    rotation: 0,
    scale: 6,
    color: 'yellow',
    iconInside:'',
    iconScale:'.5',
  },    
  {
    name: 'fourth',
    shape: 'circle(50% at 50% 50%)',
    rotation: 0,
    scale: 6,
    color: 'red',
    iconInside:'https://upload.wikimedia.org/wikipedia/commons/5/5a/Wikipedia%27s_W.svg',
    iconScale:'.5',
  },
];