export const env = {
  BD: 'mongodb://localhost:27018/BoilerPlateSvelteKitDB',
  DB_NAME: 'BoilerPlateSvelteKitDB',
  TOKEN_EXPIRY: '1h',
  URL_FRONT: 'http://127.0.0.1:1000',
  URL_FRONT_LOCAL: 'http://localhost:1000',
  URL_BACK: 'http://localhost:2000',
  PORT: 2000,
  SECRETKEY: 'kjqhfkjefhllhswfmosjgmsrdgjmdsligj',
  MAIL_HOST: 'localhost',
  MAIL_PORT: 1025,
  EMAIL_USER: 'no_reply@SvelteKit.com',
  EMAIL_PASSWORD: 'passwordTest',
  MAIL_SERVER: 'no_reply@SvelteKit.com',
  NODE_ENV: 'dev',
};
