name: Lighthouse

on:
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez cibler

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.7.0'
        
    - name: Install Lighthouse
      run: npm install -g lighthouse

    - name: Install Chromium
      run: sudo apt-get install -y chromium-browser

      
    - name: Run Lighthouse
      run: lighthouse http://localhost:1000 --output json --output-path=./lighthouse-results.json
