name: Lighthouse

on:
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez cibler

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install Lighthouse
      run: npm install -g lighthouse
      
    - name: Run Lighthouse
      run: lighthouse https://your-app.com --output json --output-path=./lighthouse-results.json
